export { FaAngular } from "@react-icons/all-files/fa/FaAngular";
export { FaYarn } from "@react-icons/all-files/fa/FaYarn";
export { FaReact } from "@react-icons/all-files/fa/FaReact";
export { FaPython } from "@react-icons/all-files/fa/FaPython";
export { FaNodeJs } from "@react-icons/all-files/fa/FaNodeJs";
export { FaFolderMinus } from "@react-icons/all-files/fa/FaFolderMinus";
export { FaArrowLeft } from "@react-icons/all-files/fa/FaArrowLeft";
export { FaPlusCircle } from "@react-icons/all-files/fa/FaPlusCircle";
export { FaWaveSquare } from "@react-icons/all-files/fa/FaWaveSquare";
// export { FaRust } from '@react-icons/all-files/fa/FaRust';
export { SiRust as FaRust } from "@react-icons/all-files/si/SiRust";
// export { FaVuejs } from '@react-icons/all-files/fa/FaVuejs';
export { SiVueDotJs as FaVuejs } from "@react-icons/all-files/si/SiVueDotJs";
export { MdErrorOutline } from "@react-icons/all-files/md/MdErrorOutline";
export { MdDone } from "@react-icons/all-files/md/MdDone";
export { MdHistory } from "@react-icons/all-files/md/MdHistory";
export { MdClear } from "@react-icons/all-files/md/MdClear";
export { CgSandClock as MdPendingActions } from "@react-icons/all-files/cg/CgSandClock";
export { MdDeleteForever } from "@react-icons/all-files/md/MdDeleteForever";
export { MdCheckCircle } from "@react-icons/all-files/md/MdCheckCircle";
export { GrDrag as MdDragIndicator } from "@react-icons/all-files/gr/GrDrag";
export { GrSettingsOption } from "@react-icons/all-files/gr/GrSettingsOption";
export { IoIosBuild } from "@react-icons/all-files/io/IoIosBuild";
export { MdArrowBack as IoArrowBack } from "@react-icons/all-files/md/MdArrowBack";
export { IoLogoNpm } from "@react-icons/all-files/io/IoLogoNpm";
export { IoIosGitMerge } from "@react-icons/all-files/io/IoIosGitMerge";
export { IoIosSearch } from "@react-icons/all-files/io/IoIosSearch";
export { IoIosCloseCircleOutline } from "@react-icons/all-files/io/IoIosCloseCircleOutline";
export { IoFileTrayFullOutline } from "@react-icons/all-files/io5/IoFileTrayFullOutline";
export { IoFolderOutline } from "@react-icons/all-files/io5/IoFolderOutline";
export { IoIosTrash } from "@react-icons/all-files/io/IoIosTrash";
export { IoIosGitPullRequest } from "@react-icons/all-files/io/IoIosGitPullRequest";
export { IoCheckboxSharp } from "@react-icons/all-files/io5/IoCheckboxSharp";
export { IoIosCheckmarkCircleOutline } from "@react-icons/all-files/io/IoIosCheckmarkCircleOutline";
export { IoIosAddCircle } from "@react-icons/all-files/io/IoIosAddCircle";
export { IoIosFlash } from "@react-icons/all-files/io/IoIosFlash";
export { VscRefresh } from "@react-icons/all-files/vsc/VscRefresh";
export { VscClose } from "@react-icons/all-files/vsc/VscClose";
export { VscTasklist } from "@react-icons/all-files/vsc/VscTasklist";
export { DiGo } from "@react-icons/all-files/di/DiGo";
export { DiNodejs } from "@react-icons/all-files/di/DiNodejs";
export { SiDotNet } from "@react-icons/all-files/si/SiDotNet";
export { SiNuget } from "@react-icons/all-files/si/SiNuget";
export { SiPypi } from "@react-icons/all-files/si/SiPypi";
export { GiCargoShip } from "@react-icons/all-files/gi/GiCargoShip";
export { BsListNested as BsBarChartSteps } from "@react-icons/all-files/bs/BsListNested";
export { FaRobot } from "@react-icons/all-files/fa/FaRobot";
export { CgSearchLoading as MdOutlineSearchOff } from "@react-icons/all-files/cg/CgSearchLoading";
export { FaChevronLeft as ChevronLeft } from "@react-icons/all-files/fa/FaChevronLeft";
export { FaChevronRight as ChevronRight } from "@react-icons/all-files/fa/FaChevronRight";
export { FaChevronDown as ChevronDown } from "@react-icons/all-files/fa/FaChevronDown";
export { BsCircleFill } from "@react-icons/all-files/bs/BsCircleFill";
export { BsBell } from "@react-icons/all-files/bs/BsBell";
export { DiAptana } from "@react-icons/all-files/di/DiAptana";
export { FaPlusSquare } from "@react-icons/all-files/fa/FaPlusSquare";
export { HiMenuAlt2 } from "@react-icons/all-files/hi/HiMenuAlt2";
export { HiOutlineX } from "@react-icons/all-files/hi/HiOutlineX";
export { HiChevronDown } from "@react-icons/all-files/hi/HiChevronDown";

export { HiLocationMarker } from "@react-icons/all-files/hi/HiLocationMarker";
export { FaPen } from "@react-icons/all-files/fa/FaPen";
export { FaUpload } from "@react-icons/all-files/fa/FaUpload";
export { FaRegUser } from "@react-icons/all-files/fa/FaRegUser";
