import type { NextPage } from "next";
import Head from "next/head";
import { Header, ReactIcon } from "../components";
import Slider from "../components/slider/slider";
import Product from "./product/product";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home | Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo2.jpg" />
      </Head>

      <main className="w-full">
        <Header />
        <ReactIcon icon="BsBell" className="w-12 h-12" />
        <Product />
        <Slider />
      </main>

      <footer className="bg-red-300">
        <div className="container max-w-4xl mx-auto py-16 text-center break-normal">
          <p className="text-black font-extrabold text-3xl md:text-5xl">
            Trippers.Pk
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Home;
