import type { NextPage } from "next";
import Head from "next/head";
import { Header, ReactIcon } from "../components";
import Category from "../components/category/category";
import Footer from "../components/footer/footer";
import Dreams from "../components/home";
import Slider from "../components/slider/slider";
import Product from "./product/product";

const Home: NextPage = () => {
  
  return (
    <div>
      <Head>
        <title>Home | Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo2.jpg" />
      </Head>

      <main className="w-full">
        <Header />
        <Dreams />
        <Category />
        <Product />
        <Slider />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export default Home;
